Decode pattern
angular-ui/ui-mention pull request #35
Opened 2016-11-03 13:21 UTC by biggieman

I think this is the easiest way to do with backward compatibility
#24

2016-11-03 21:33 UTC, ProLoser requested changes

2016-11-03 21:33 UTC, ProLoser commented on dist/mention.js
> +    return value ? value.replace(this.decodePattern(), '$1') : '';
Wouldn't it make more sense to make this a property instead of a function, similar to `this.pattern`?

2016-11-04 06:56 UTC, biggieman commented on dist/mention.js
> +    return value ? value.replace(this.decodePattern(), '$1') : '';
I chose between function and property. I looked at the function `this.encode` and I think, that `this.decodePattern` is similar to `this.encode` logic.

2016-11-04 07:17 UTC, ProLoser commented on dist/mention.js
> +    return value ? value.replace(this.decodePattern(), '$1') : '';
But there's literally `this.decode()` to go with `this.encode()` so wouldn't `this.pattern` become `this.encodePattern` and then `this.decodePattern` would match it?

2016-11-04 14:31 UTC, biggieman commented on dist/mention.js
> +    return value ? value.replace(this.decodePattern(), '$1') : '';
But `this.pattern` is not used by `this.encode()` function. 
I think that the best name for this property is `this.triggerPattern` or `this.searchPattern`.

And I agree that `this.decodePattern` can be a property.

2016-11-04 18:05 UTC, ProLoser commented on dist/mention.js
> +    return value ? value.replace(this.decodePattern(), '$1') : '';
Touché.

2016-11-04 20:03 UTC, ProLoser commented on dist/mention.js
> +    return value ? value.replace(this.decodePattern(), '$1') : '';
I pushed a new travis file to master, if you rebase your PR it should fix your build errors.

2016-11-07 07:33 UTC, biggieman commented
Changed `this.decodePattern()` from function to property. Renamed `this.pattern` to `this.searchPattern`

2016-11-07 22:37 UTC, ProLoser approved these changes

2016-11-07 22:38 UTC, ProLoser commented
Looks good. I may leave this to you to merge in as this is a slightly backwards incompatible change and should probably be pushed to a new (at least minor) version release.

2016-11-08 06:58 UTC, biggieman commented
@ProLoser As you wish. And i also could change back to `this.pattern` for backward compatibility.

2016-11-08 19:42 UTC, ProLoser commented
I'm indifferent.

2016-12-13 06:53 UTC, closed without merging