Issue40 fix crush
angular-ui/ui-mention pull request #41
Opened 2016-12-12 07:47 UTC by biggieman

I think only one place need fix.

2016-12-12 15:46 UTC, Jexordexan commented
Thanks for fixing this! I noticed there are other places that may throw an error on a bad choice selection. Namely `this.label()` and `this.encode()` 
I'm aware that the developer can override these methods and put in their own null checks, but I believe they should work by default. I've fixed mine by just putting `choice &&` before the return value. A simple short circuit does the trick!

2016-12-12 19:20 UTC, ProLoser commented on example/example.js
> +}]).directive('mentionExample', function () {
Is there a reason for this change?

2016-12-12 19:22 UTC, ProLoser requested changes
I don't think the modification to the example file is necessary. If you remove it I'll merge in this change.

2016-12-12 19:25 UTC, ProLoser commented
Along with #35 I prefer NOT to use the more explicit injection syntax because that should be handled by a preprocessor so that the source code can be minimal. Additionally, the minified version of the example does NOT rename the variable, voiding the need for this injection syntax. Finally, there's no reason for anyone to re-process the example file itself since it's only an example.

2016-12-13 06:17 UTC, biggieman commented on example/example.js
> +}]).directive('mentionExample', function () {
Yes, it's not necessary for example, but on original gulpfile.js task `scripts:example` pipes ngAnnotate (like main `scripts`)

2016-12-13 06:29 UTC, biggieman commented
@ProLoser: remove annotates from this pull and #35
@Jexordexan this functions used at ngModel rendering and we breaks render in `this.select()`.

2016-12-13 06:32 UTC, merged